name: Upload to NPM.com

on:
  push:
    branches:
      - 'release/**'
      - '!release/**-snapshot'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.13.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: quality gate
        run: |
          npm prune
          npm i
          npm run test:coverage
      - name: Deploy to npm.com
        if: "contains(github.event.head_commit.message, 'Release')"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm run build
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          npm publish  --access=public
###